### ISSUE TITLE
running SyVOLT

### ISSUE THREAD

**Issue by anyaa431** [levilucio/SyVOLT#12]
Hi,

I have a problem to run SyVOLT. For running an example with SyVOLT, I created general/PyDev project and copying the files of https://github.com/levilucio/SyVOLT/tree/master/eclipse_integration to it.
then e.g. for running verify_fam_extended.xml, I changed address in lines 6 and 73 of this file. I don't know exactly what are these adresses. It means, if I download https://github.com/levilucio/SyVOLT in my "Downloads" folder, Is it true to write these addresses?

6: location="C:\Users\Sony\Downloads\SyVOLT-master\SyVOLT-master"
73:   dir="C:\Users\Sony\Downloads\SyVOLT-master\SyVOLT-master\models_to_text_scripts"

In Windows, I have some different errors when I running the xml file via ant (In the configuration, I checked main in Target and selected Run in the same JRE as the Workspace):
- File "toplevel.py", line 37
self.transformation_directory = "C:\Users\Sony\Desktop\Project\Workspace\test3\backend\generated/transformation"
           ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
- Traceback (most recent call last):
File "toplevel.py", line 2, in <module>
from util.parser import load_parser
ImportError: No module named 'util'

On Mac OS X (Captain):
I have the below error:
libpl (shared) not found. Possible reasons:
SWI-Prolog not installed as a shared library. Install SWI-Prolog (5.6.34 works just fine)

First, I install version 7.4.1 of Prolog, then I uninstalled it and installed swi-prolog-5.6.64-leopard-powerpc.mpkg.zip.
or
        [exec] Traceback (most recent call last):
        [exec]   File "toplevel.py", line 4, in <module>
        [exec]     from util.test_script_base import Test
        [exec]   File "/Users/apple/Downloads/SyVOLT-master/util/test_script_base.py", line 3, in <module>
        [exec]     from path_condition_generator import PathConditionGenerator
        [exec]   File "/Users/apple/Downloads/SyVOLT-master/path_condition_generator.py", line 3, in <module>
        [exec]     from core.himesis_utils import disjoint_model_union
        [exec]   File "/Users/apple/Downloads/SyVOLT-master/core/himesis_utils.py", line 12, in <module>
        [exec]     from importlib import invalidate_caches
        [exec] ImportError: cannot import name invalidate_caches

Many thanks for your time,

**Comment by anyaa431** [comment]
@clagms Would you please help me in this regard?

**Comment by BentleyJOakes** [comment]
This should be fixed by commit df5e9cdf988a68b7ec3941411fa18fbb2bf13a21. It tries to import invalidate_caches if the file import fails. But this function is only available in Python 3, so an error message is reported.
