### ISSUE TITLE
Select path conditions having mandatory containment relations

### ISSUE THREAD

**Issue by levilucio** [levilucio/SyVOLT#2]
We now keep around path conditions than cannot exist because they violate metamodel constraints in terms of mandatory containment relations. These path conditions should be discarded, but that can only happen at the end of the path condition generation.

1. parse all containment links in the metamodel
2. build dependencies of containment links for all types in the metamodel
3. identify which rules build each containment link
4. after / before the PC is built, check whether given the elements in it, it is still possible to build the missing containment links for all types existing in the PC. This can be achieved by just looking at the types in the PC and not at the elements themselves

4.1. check for a PC the set of types of instances that are already built in the output model
4.2. check the containment dependencies for those types (have to OR multiple containment relations going into the same class)
4.3. check which containment dependencies have already been built by previous rules and subtract them from the containment dependencies for types existing in the path condition
4.4. get the result from 4.3 and remove from it the dependencies built by the rules still remaining to execute. If the result is different from the empty set, take the PC out of the set of PCs to be considered for the final PC set

**Comment by BentleyJOakes** [comment]
Closing as pruning is implemented
