### ISSUE TITLE
overlapping rules of isolated elements

### ISSUE THREAD

**Issue by levilucio** [levilucio/SyVOLT#7]
we are not considering partial overlaps of isolated elements, when they absolutely have to overlap .For example if a rule has as match "A B" and the other "B C", with no connections between them, the B's will ALWAYS execute together

**Comment by BentleyJOakes** [comment]
I believe the current implementation of subsumption is correct. Rules are compared using the standard isomorphic, non-link based matcher.

Could you elaborate if you still think this is an issue?

**Comment by levilucio** [comment]
This does not seem to be an issue. It falls in the standard case of symbolic execution of different non-overlapping rules.
