### ISSUE TITLE
strategy for discarding PCs during PC construction

### ISSUE THREAD

**Issue by levilucio** [levilucio/SyVOLT#8]
PCs can be discarded by building the PC space depth first and including waypoints at given rules in layers, such that the space is searched not in it's totality breadth first, but by chunks. When a chunk is done (all rules of that slice are executed), PC's that don't respect the containment relations can be thrown away, diminishing the number of PCs that have to be tracked either in memory or in disk. Have to be careful with partial or total overlaps though, and the waypoints should not occur in such layers because of the dependency between rules in the same layer that occurs then.

Needs PC selection to occur based on violation of the containment laws in the metamodel.

**Comment by BentleyJOakes** [comment]
Closed due to implementation of pruning.
Note that this pruning is done at the end of a path condition construction worker. Therefore, the more rounds, and the more workers, the more PCs that will be pruned.
